# Generated by Django 4.2.7 on 2023-11-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnochRecoveryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='OrientationRequest',
        ),
    ]
